apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: node-app
    buildpacks:
      builder: paketobuildpacks/builder:full
deploy:
  kubectl:
    manifests:
    - kubernetes/service.yml
    - kubernetes/deployment.yml
portForward:
  - resourceType: service
    resourceName: node-app
    port: 80
    localPort: 3000
profiles:
- name: local
  build:
    local:
      push: false
