apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-app
  name: node-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: node-app